### ISSUE TITLE
Editing profile is broken

### ISSUE THREAD

**Issue by jfly** [jfly/gjcomps#111]
When I click save, all i see is "Error submitting form!"

In the console:

Error in profileForm update errorClass: Access denied [403]details: undefinederror: 403errorType: "Meteor.Error"message: "Access denied [403]"reason: "Access denied"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: Middle

**Comment by jbcm627** [comment]
Things seem to have broken when adding the createdAt and updatedAt fields in 5a0796467231ec081993554611957dfeaae1e4d4.  I did blindly add these in without testing; I'm not sure what is wrong though.
