### ISSUE TITLE
Limit size of registration

### ISSUE THREAD

**Issue by jfly** [jfly/gjcomps#39]
I don't know if this should be a per event limit, or an overall limit on the size of the competition.

@jbcm627 could you comment on what, if anything, cubingusa does here?

I'm unsure if this needs to be done for Phase 1.

**Comment by jbcm627** [comment]
Size is currently limited so that no new registrations can be added once limits are hit.  Existing registrations can still be changed though (including number of guests).

**Comment by jfly** [comment]
I guess that's slightly unintuitive behavior, but it seems fine to me.
