### ISSUE TITLE
Edit profile page needs to actually do something

### ISSUE THREAD

**Issue by jfly** [jfly/gjcomps#53]
Make sure competitors can edit:
 - [x] birthday
 - [x] name
 - [x] citizenship (country)
 - [x] gender
 - [x] email
 - [x] WCA id
before they register.

Other ideas include:
 - #100
 - #24 
 - #101 
 - #110

**Comment by jbcm627** [comment]
I've edited the first comment to list some ideas, and made separate issues for future ideas.  I'm going to close this ticket as the profile page actually does do something now.
