### ISSUE TITLE
(re)consider layout of the data entry page

### ISSUE THREAD

**Issue by jfly** [jfly/gjcomps#90]
Right now, we're just a floating data entry sidebar, and a long list of results. @keemy pointed out that this long list of results is probably not that useful. We should sit down and think about what a good use for this screen real estate could be.

**Comment by jbcm627** [comment]
Digging back through old threads for ideas ([here](https://www.speedsolving.com/forum/showthread.php?35560-cubecomps-com-for-delegates-and-organizers)) brings up this:
> while typing in results, it would be useful to be able to add/remove competitors from an event without having to leave the page.

Which is an idea I think I still like.
