### ISSUE TITLE
Registration quirk?

### ISSUE THREAD

**Issue by jbcm627** [jfly/gjcomps#99]
I'm getting this message:
>W20150102-00:48:03.440(-5)? (STDERR) error on fast-rendering path: /rsQuX82dwMDNRGido/registration ; error: TypeError: Cannot call method 'call' of undefined
>W20150102-00:48:03.442(-5)? (STDERR)     at Object.Router.route.waitOn (app/both/routes.js:310:52)
>W20150102-00:48:03.458(-5)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/iron_router_support.js:83:1
>W20150102-00:48:03.458(-5)? (STDERR)     at Array.forEach (native)
>W20150102-00:48:03.459(-5)? (STDERR)     at Context.onRoute (packages/meteorhacks:fast-render/lib/server/iron_router_support.js:82:1)
>W20150102-00:48:03.459(-5)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/fast_render.js:45:1

Conditions to reproduce:
I have 2 users.  One is registered, one is not; both have sessions open, looking at the registration page.  The current code allows users who are already registered to change their registration despite competitor limits.  When I make a change to the user who is registered, this error appears.  I'm not sure which session causes the error.

Everything seems to be working correctly despite this?

**Comment by jfly** [comment]
I think all you need to produce this is to visit the /registration page "cold" (by hitting f5 or browsing there directly somehow). That's the only way the fast-render code is engaged, so it makes sense that that's how you'd reproduce this. I'll look into this bug.
